/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nihal gupta
 */
public class AddProductScreen extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    String gotusername = null;

    /**
     * Creates new form AddProductScreen
     */
    public AddProductScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        et_pname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        info = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        btn_upload = new javax.swing.JButton();
        cb_quantity = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_category = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        et_price = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Register Shop");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Add Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 13, 240, 47));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Product Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        et_pname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        et_pname.setToolTipText("");
        getContentPane().add(et_pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 241, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Price");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 203, 351, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_upload.setBackground(new java.awt.Color(102, 102, 102));
        btn_upload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_upload.setText("Upload");
        btn_upload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_upload.setVerifyInputWhenFocusTarget(false);
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel1.add(btn_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 136, 38));

        cb_quantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" ,"5" }));
        cb_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_quantityActionPerformed(evt);
            }
        });
        jPanel1.add(cb_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 351, 37));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Category");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Rs.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Quantity");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        cb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grocery", "cosmetics", "sports", "clothing" ,"electronics" }));
        cb_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoryActionPerformed(evt);
            }
        });
        jPanel1.add(cb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 351, 37));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Info");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        et_price.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        et_price.setToolTipText("");
        jPanel1.add(et_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 210, -1));

        btn_cancel.setBackground(new java.awt.Color(102, 102, 102));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Info");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getUsername(String str) {
        gotusername = str;
    }
    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        System.out.println(cb_category.getSelectedItem().toString());
        System.out.println(cb_quantity.getSelectedItem().toString());
        if (!et_pname.getText().isEmpty() && !et_price.getText().isEmpty() && !info.getText().isEmpty()) {
            try {  //jdbc:mysql://localhost:3306/cakemarket?user=root&password=Jayshree123
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo?user=root&password=nihal123");
                ps = con.prepareStatement("insert into product(pname,Price,info,category,quantity,shopinfo) values(?,?,?,?,?,?)");
                ps.setString(1, et_pname.getText());
                ps.setInt(2, Integer.parseInt(et_price.getText()));
                ps.setString(3, info.getText());
                ps.setString(4, cb_category.getSelectedItem().toString());
                ps.setInt(5, Integer.parseInt(cb_quantity.getSelectedItem().toString()));
                ps.setString(6, gotusername);
                ps.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Uploaded Successfully!!", "Successfull", JOptionPane.INFORMATION_MESSAGE);
            ChooseScreen choose = new ChooseScreen();
            choose.setVisible(true);
            choose.setLocationRelativeTo(null);
            this.dispose();
        }


    }//GEN-LAST:event_btn_uploadActionPerformed

    private void cb_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_quantityActionPerformed

    private void cb_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoryActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cb_categoryActionPerformed

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        // TODO add your handling code here
        ChooseScreen choose = new ChooseScreen();
        choose.setVisible(true);
        choose.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        ChooseScreen choose = new ChooseScreen();
        choose.setVisible(true);
        choose.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_upload;
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JComboBox<String> cb_quantity;
    private javax.swing.JTextField et_pname;
    private javax.swing.JTextField et_price;
    private java.awt.TextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
