/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.JOptionPane;

/**
 *
 * @author Nihal gupta
 */
public class MainScreen extends javax.swing.JFrame {

    int gotpid;
    String cusername = null;
    DefaultTableModel model = null;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        super("Main Screen");
        Connection con;
        PreparedStatement ps;
        ImageIcon image = null;

        model = new DefaultTableModel() {

//            private static final long serialVersionUID = 1L;
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        model.addColumn("Category");
        model.addColumn("Item");
        model.addColumn("Price");
        model.addColumn("Qty");
        model.addColumn("id");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo?user=root&password=nihal123");
            CallableStatement sp = con.prepareCall("select i.smallimage,p.pname,p.price,p.quantity,p.pid from image i,product p where i.category = p.category;");
            ResultSet rs = sp.executeQuery();
            while (rs.next()) {
                byte[] imagedata = rs.getBytes("smallimage");
                image = new ImageIcon(imagedata);
                model.addRow(new Object[]{image, rs.getString("pname"), rs.getInt("price"), rs.getInt("quantity"), rs.getInt("pid")});

            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        initComponents();
        jTable1.setRowHeight(133);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        JTableHeader header = jTable1.getTableHeader();
        header.setDefaultRenderer(centerRenderer);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultRenderer(Integer.class, centerRenderer);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
//        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        btn_feedback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cb_filter = new javax.swing.JComboBox<>();
        btn_apply = new javax.swing.JButton();
        et_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setText("Log-out");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 80, -1));

        btn_feedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_feedback.setText("Feedback");
        btn_feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_feedbackMouseClicked(evt);
            }
        });
        jPanel1.add(btn_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("E - Commerce");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 47));

        jTable1.setModel(model);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 830, 590));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seacrh");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 50, 30));

        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Cosmetics", "Clothing", "Sports" , "Electronics","All" }));
        jPanel1.add(cb_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, 30));

        btn_apply.setText("Apply");
        btn_apply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_applyMouseClicked(evt);
            }
        });
        jPanel1.add(btn_apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 30));

        et_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_searchKeyReleased(evt);
            }
        });
        jPanel1.add(et_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Filter");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getCusername(String str) {
        cusername = str;
    }
    private void btn_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feedbackMouseClicked
        // TODO add your handling code here:
        FeedbackScreen feedback = new FeedbackScreen();
        feedback.setVisible(true);
        feedback.setLocationRelativeTo(null);
        feedback.getCusernameHere(cusername);
        this.dispose();
    }//GEN-LAST:event_btn_feedbackMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Sure? You want to LogOut?", "Alert", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ChooseScreen choose = new ChooseScreen();
            choose.setVisible(true);
            choose.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int column = 4;
//        System.out.println(jTable1.getValueAt(row, column));
        gotpid = (int) jTable1.getValueAt(row, column);
        System.out.println(gotpid);
        BuyScreen buyscreen = new BuyScreen(gotpid);
        buyscreen.setVisible(true);
        buyscreen.getUserName(cusername);
        buyscreen.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_applyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_applyMouseClicked

        int selecteditem = cb_filter.getSelectedIndex();
        Connection con;
        PreparedStatement ps;
        ImageIcon image = null;

        model = new DefaultTableModel() {

//            private static final long serialVersionUID = 1L;
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        model.addColumn("Category");
        model.addColumn("Item");
        model.addColumn("Price");
        model.addColumn("Qty");
        model.addColumn("id");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo?user=root&password=nihal123");
            PreparedStatement sp = con.prepareStatement("select i.smallimage,p.pname,p.price,p.quantity,p.pid from image i,product p where i.category = p.category and p.category like ?;");
            if (selecteditem == 0) {
                sp.setString(1, "grocery");
            } else if (selecteditem == 1) {
                sp.setString(1, "cosmetics");
            } else if (selecteditem == 2) {
                sp.setString(1, "clothing");
            } else if (selecteditem == 3) {
                sp.setString(1, "sports");
            } else if (selecteditem == 4) {
                sp.setString(1, "electronics");
            } else if (selecteditem == 5) {
                sp.setString(1, "%");
            }
            ResultSet rs = sp.executeQuery();
            while (rs.next()) {
                byte[] imagedata = rs.getBytes("smallimage");
                image = new ImageIcon(imagedata);
                model.addRow(new Object[]{image, rs.getString("pname"), rs.getInt("price"), rs.getInt("quantity"), rs.getInt("pid")});

            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        jTable1.setRowHeight(133);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        JTableHeader header = jTable1.getTableHeader();
        header.setDefaultRenderer(centerRenderer);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultRenderer(Integer.class, centerRenderer);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
        jTable1.setModel(model);
    }//GEN-LAST:event_btn_applyMouseClicked

    private void et_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_searchKeyReleased
        // TODO add your handling code here:
        String textnow = et_search.getText();
        Connection con;
        PreparedStatement ps;
        ImageIcon image = null;

        model = new DefaultTableModel() {

// private static final long serialVersionUID = 1L;
// Returning the Class of each column will allow different
// renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        model.addColumn("Category");
        model.addColumn("Item");
        model.addColumn("Price");
        model.addColumn("Qty");
        model.addColumn("id");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo?user=root&password=nihal123");
            PreparedStatement sp = con.prepareStatement("select i.smallimage,p.pname,p.price,p.quantity,p.pid from image i,product p where i.category = p.category and p.pname like ?;");
            sp.setString(1, textnow+"%");
            ResultSet rs = sp.executeQuery();
            while (rs.next()) {
                byte[] imagedata = rs.getBytes("smallimage");
                image = new ImageIcon(imagedata);
                model.addRow(new Object[]{image, rs.getString("pname"), rs.getInt("price"), rs.getInt("quantity"), rs.getInt("pid")});

            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        jTable1.setRowHeight(133);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        JTableHeader header = jTable1.getTableHeader();
        header.setDefaultRenderer(centerRenderer);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultRenderer(Integer.class, centerRenderer);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
        jTable1.setModel(model);
    }//GEN-LAST:event_et_searchKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apply;
    private javax.swing.JLabel btn_feedback;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JTextField et_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
